module.exports = {
  1: 'https://www.rabotniki.ua/price/vnutrennyaya-otdelka/?region=1',
  2:	'https://www.rabotniki.ua/price/vnutrennyaya-otdelka/?region=5',
  3:	'https://www.rabotniki.ua/price/vnutrennyaya-otdelka/?region=19',
  4:	'https://www.rabotniki.ua/price/vnutrennyaya-otdelka/?region=22',
  5:	'https://lviv.rabotniki.ua/price/vnutrennyaya-otdelka/',
  6:	'https://www.rabotniki.ua/price/vnutrennyaya-otdelka/?region=24',
  7:	'https://www.rabotniki.ua/kharkov/price/vnutrennyaya-otdelka/',
  8:	'https://www.rabotniki.ua/price/vnutrennyaya-otdelka/?region=18',
  9:	'https://www.rabotniki.ua/price/vnutrennyaya-otdelka/?region=17',
  10:	'https://www.rabotniki.ua/price/vnutrennyaya-otdelka/?region=9',
  11:	'https://dnepr.rabotniki.ua/price/vnutrennyaya-otdelka/',
  12:	'https://odessa.rabotniki.ua/price/vnutrennyaya-otdelka/',
  13:	'https://www.rabotniki.ua/price/vnutrennyaya-otdelka/?region=4',
  14:	'https://zaporozhye.rabotniki.ua/price/vnutrennyaya-otdelka/',
  15:	'https://www.rabotniki.ua/price/vnutrennyaya-otdelka/?region=8',
  16:	'https://www.rabotniki.ua/price/vnutrennyaya-otdelka/?region=10',
  17:	'https://www.rabotniki.ua/price/vnutrennyaya-otdelka/?region=11',
  18:	'https://www.rabotniki.ua/price/vnutrennyaya-otdelka/?region=2',
  19:	'https://www.rabotniki.ua/price/vnutrennyaya-otdelka/?region=13',
  20:	'https://www.rabotniki.ua/price/vnutrennyaya-otdelka/?region=15',
  21:	'https://www.rabotniki.ua/price/vnutrennyaya-otdelka/?region=16',
  22:	'https://www.rabotniki.ua/price/vnutrennyaya-otdelka/?region=6',
  23:	'https://www.rabotniki.ua/price/vnutrennyaya-otdelka/?region=21',
  24:	'https://www.rabotniki.ua/price/vnutrennyaya-otdelka/?region=23',
  25:	'https://www.rabotniki.ua/price/vnutrennyaya-otdelka/?region=25',
};
