module.exports = {
  works: {
    // chornova
    GRUNTOVKA_POD_STYAZHKU: 1,
    CEMENTNO_PESCHANAYA_STYAZHKA: 2,
    GRUNTOVKA_STEN_POTOLKA: 3,
    PODGOTOVKA_BETONNOGO_POTOLKA: 4,
    PODGOTOVKA_BETONNOJ_STENY: 5,
    GRUNTOVKA_STYAZHKI_POD_PLITKU: 6,

    // chistova
    UKLADKA_PLITKI_NA_POL: 7,
    UKLADKA_PLITKI_NA_STENYI: 8,
    POKLEYKA_OBOEV_NA_STENU: 9,
    UKLADKA_LAMINATA: 10,
    UKLADKA_PARKETNOY_DOSKI_NA_POL: 11,
    UKLADKA_TREHSLOYNOY_PARKETNOY_DOSKI_NA_POL: 12,
    POKRASKA_STEN_VODOEMULSIONNOY_KRASKOY: 13,
    POKRASKA_POTOLKA_VODOEMULSIONNOY_KRASKOY: 14,
    MONTAZH_NATYAZHNYIH_POTOLKOV: 15,
  },
};
